---
- name: Clean unnecessary files
  hosts: default
  become: true
  tasks:
    - name: Docker prune
      ansible.builtin.include_tasks: tasks/docker.yml
      when: "'docker' in group_names"
      tags: docker

    - name: APT autoremove
      ansible.builtin.include_tasks: tasks/apt.yml
      when: "'apt' == ansible_pkg_mgr"
      tags: apt

    - name: Plex shrub
      ansible.builtin.include_tasks: tasks/plex.yml
      when: inventory_hostname == "plex"
      tags: plex
