---
- name: Pip install docker
  ansible.builtin.pip:
    name:
      - docker
      - docker-compose

- name: Docker compose restart
  community.docker.docker_compose:
    project_src: "{{ docker_compose_path }}"
    build: "{{ ansible_env.UPDATE | default('false') | bool }}"
    state: present
    restarted: true
  
