pipeline {
    agent any

    parameters {
        booleanParam(
            name: 'REALLY',
            description: "Restarting Plex will disturb users currently watching. Are you sure?")
        booleanParam(
            name: 'UPDATE',
            description: "Want to update the service while we're at it?")
    }


    stages {
        stage('Checkout') {
            steps {
                // Checkout your source code from version control
                checkout scm
            }
        }

        stage('Run Ansible Playbook') {
            steps {
                ansiblePlaybook(
                    playbook: 'fix-plex/main.yml',
                    inventory: 'inventory.ini')
            }
        }
    }

    post {
        success {
            script {
                def msg = "I did some things so RTV might work again"
                sh "curl -d '${msg}' ${NOTIFY_URL}"
                echo "${msg}"
            }
        }
        failure {
            script {
                def msg = "I tried to fix RTV, but failed"
                sh "curl -d '${msg}' ${NOTIFY_URL}"
                echo "${msg}"
            }
        }
    }
}
