pipeline {
    agent any

    options {
        ansiColor('xterm')
    }

    parameters {
        booleanParam(
            name: 'REALLY',
            description: "Restarting Plex will disturb users currently watching. Are you sure?")
        booleanParam(
            name: 'UPDATE',
            description: "Want to update the service while we're at it?")
    }


    stages {
        stage('Checkout') {
            steps {
                // Checkout your source code from version control
                checkout([$class: 'GitSCM',
                          branches: [[name: '*/main']],
                          doGenerateSubmoduleConfigurations: false,
                          extensions: [[$class: 'SubmoduleOption',
                                        disableSubmodules: false,
                                        parentCredentials: true,
                                        recursiveSubmodules: true,
                                        reference: '',
                                        trackingSubmodules: true]],
                          submoduleCfg: [],
                          userRemoteConfigs: [[credentialsId: 'jenkins-ssh-id',
                              url: 'git@github.com:romanpeters/maintenance-playbooks.git']]])
            }
        }

        stage('Run Ansible Playbook') {
            steps {
                ansiblePlaybook(
                    playbook: 'fix-plex/main.yml',
                    inventory: 'infrastructure/inventory.ini',
                    colorized: true,
                    extraVars: {
                       extraVar("restart_plex", params.REALLY, false),
                       extraVar("update", params.UPDATE, false)})
            }
        }
    }

    post {
        success {
            script {
                def msg = "I did some things so RTV might work again"
                sh "curl -d '${msg}' ${NOTIFY_URL}"
                echo "${msg}"
            }
        }
        failure {
            script {
                def msg = "I tried to fix RTV, but failed"
                sh "curl -d '${msg}' ${NOTIFY_URL}"
                echo "${msg}"
            }
        }
    }
}
