pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Checkout your source code from version control
                checkout scm
            }
        }

        stage('Run Ansible Playbook') {
            steps {
                script {
                    // Set the path to your Ansible playbook and inventory file
                    def ansiblePlaybook = "fix-plex/main.yml"
                    def ansibleInventory = "inventory.ini"

                    // Run the Ansible playbook using the 'ansible-playbook' command
                    sh "ansible-playbook -i ${ansibleInventory} ${ansiblePlaybook}"
                }
            }
        }
    }

    post {
        success {
            script {
                def msg = "I did some things so RTV might work again"
                sh "curl -d '${msg}' ${NOTIFY_URL}"
                echo "${msg}"
            }
        }
        failure {
            script {
                def msg = "I tried to fix RTV, but failed"
                sh "curl -d '${msg}' ${NOTIFY_URL}"
                echo "${msg}"
            }
        }
    }
}
