---
- name: Fix Plex
  hosts: plex
  become: true
  gather_facts: false
  tasks:
    - name: Restart Plex
      ansible.builtin.include_tasks: tasks/plex.yml

- name: Restart VPN and web Docker containers
  hosts: romantv,nuc
  gather_facts: false
  tasks:
    - name: Restart Docker
      ansible.builtin.include_tasks: tasks/restart_docker.yml
