---
- name: Copy server key
  hosts: default
  become: true
  become_user: "{{ username }}"
  tasks:
    - name: Create the ~/.credentials directory
      ansible.builtin.file:
        path: ~/.credentials
        state: directory
        mode: '0700'

    - name: Write text to server.age file
      ansible.builtin.copy:
        dest: ~/.credentials/server.age
        content: "{{ server_key }}"
        mode: '0600'
