pipeline {
    agent any

    parameters {
        string(name: 'INSTANCE',
            description: 'Specify the instance variable')
        string(name: 'TAGS',
            description: 'Options: docker, production')
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout your source code from version control
                checkout scm
            }
        }

        stage('Run Ansible Playbook') {
            steps {
                ansiblePlaybook(
                    playbook: 'server/main.yml',
                    inventory: 'inventory.ini',
                    extras: '-e instance="$INSTANCE"')

            }
        }
    }
}

