pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Checkout your source code from version control
                checkout scm
            }
        }

        stage('Run Ansible Playbook') {
            steps {
                script {
                    // Set the path to your Ansible playbook and inventory file
                    def ansiblePlaybook = "apt-update/main.yml"
                    def ansibleInventory = "inventory.ini"

                    // Run the Ansible playbook using the 'ansible-playbook' command
                    sh "ansible-playbook -i ${ansibleInventory} ${ansiblePlaybook}"
                }
            }
        }
    }

    post {
        success {
	    sh "curl -d 'System updated' ${NOTIFY_URL}"
            echo 'Ansible playbook executed successfully'
        }
        failure {
	    sh "curl -d 'System update failed' ${NOTIFY_URL}"
            echo 'Ansible playbook execution failed'
        }
    }
}
