pipeline {
    agent any

    parameters {
        choice choices: ['all', 'default', 'nuc'], 
        description: 'Choose which host or host group.', 
        name: 'Host'
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout your source code from version control
                checkout scm
            }
        }

        stage('Run Ansible Playbook') {
            steps {
                ansiblePlaybook {
                    inventory: 'inventory.ini',
                    limit: 'default',
                    playbook: 'apt-update/main.yml'
                }
            }
        }
    }

    post {
        success {
            script {
                def msg = "Updated your servers"
                sh "curl -d '${msg}' ${NOTIFY_URL}"
                echo "${msg}"
            }
        }
        failure {
            script {
                def msg = "I failed to update your servers"
                sh "curl -d '${msg}' ${NOTIFY_URL}"
                echo "${msg}"
            }
        }
    }
}
