---
- name: Install package updates
  hosts: proxmox_ubuntu_guests,proxmox,octopi

  tasks:
    - name: update and upgrade apt packages
      become: yes
      apt:
        upgrade: yes
        update_cache: yes
        autoremove: yes
