---
- name: Configure server
  hosts: "{{ instance }}"
  become: true
  roles:
    - name: base

    - name: docker
      tags: [docker, never]

    - name: production
      tags: [production, never]
