pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Checkout your source code from version control
                checkout scm
            }
        }

        stage('Run Ansible Playbook') {
	    when {
                expression { params.REALLY == true }
            }
            steps {
                script {
                    // Set the path to your Ansible playbook and inventory file
                    def ansiblePlaybook = "reboot-router/main.yml"
                    def ansibleInventory = "reboot-router/inventory.ini"

                    // Run the Ansible playbook using the 'ansible-playbook' command
                    sh "ansible-playbook -i ${ansibleInventory} ${ansiblePlaybook}"
                }
            }
        }
    }

    post {
        success {
            script {
                def msg = "Router was rebooted"
                sh "curl -d '${msg}' ${NOTIFY_URL}"
                echo "${msg}"
            }
        }
        failure {
            script {
                def msg = "I tried to reboot your router, but failed"
                sh "curl -d '${msg}' ${NOTIFY_URL}"
                echo "${msg}"
            }
        }
    }
}

