pipeline {
    agent any

    environment {
        ROUTER_PASSWORD = credentials('router-password')
    }

   parameters {
        booleanParam(
            name: 'REALLY',
            description: "Rebooting the router will temporarily make the internet unavailable. Are you sure?")
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout your source code from version control
                checkout scm
            }
        }

        stage('Run Ansible Playbook') {
	    when {
                expression { params.REALLY == true }
            }
            steps {
                ansiblePlaybook(
                    playbook: 'reboot-router/main.yml',
                    inventory: 'inventory.ini')
            }
        }
    }

    post {
        success {
            script {
                def msg = "Router was rebooted"
                sh "curl -d '${msg}' ${NOTIFY_URL}"
                echo "${msg}"
            }
        }
        failure {
            script {
                def msg = "I tried to reboot your router, but failed"
                sh "curl -d '${msg}' ${NOTIFY_URL}"
                echo "${msg}"
            }
        }
    }
}

