---
- name: Reboot router
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Get CSRFToken
      ansible.builtin.uri:
        url: http://{{ hostvars['router']['ansible_host'] }}/cgi-bin/reboot.sh
        validate_certs: false
        user: admin
        password: "{{ lookup('env', 'ROUTER_PASSWORD') }}"
        method: GET
        return_content: true
        status_code: 200
      register: page_response

    - name: Extract CSRFToken
      ansible.builtin.set_fact:
        csrf_token: "{{ page_response.content | regex_findall('name=\"CSRFToken\" lang=\"en\" value=\"(.*?)\"') | first }}"

    - name: Reboot router
      ansible.builtin.uri:
        url: http://{{ hostvars['router']['ansible_host'] }}/cgi-bin/reboot.sh
        validate_certs: false
        user: admin
        password: "{{ lookup('env', 'ROUTER_PASSWORD') }}"
        method: POST
        force_basic_auth: true
        status_code: 200
        body_format: form-urlencoded
        body:
          CSRFToken: "{{ csrf_token }}"
          reboot: Reboot

    - name: Wait for the router to shutdown
      ansible.builtin.wait_for:
        timeout: 30
      delegate_to: localhost

    - name: Wait until back online
      ansible.builtin.uri:
        url: http://{{ hostvars['router']['ansible_host'] }}/
        return_content: true
        status_code:
          - 401
      until: uri_output.status == 401
      retries: 120 # Retries for 120 * 5 seconds = 10 minutes
      delay: 5
      register: uri_output
