pipeline {
    agent any

    parameters {
        choice(choices: ['default', 'all', 'nuc'],
               description: "Choose which host or host group.",
               name: 'TARGET')
    }

    stages {
        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Checkout') {
            steps {
                // Checkout your source code from version control
                checkout([$class: 'GitSCM', 
                          branches: [[name: '*/main']], 
                          doGenerateSubmoduleConfigurations: false, 
                          extensions: [[$class: 'SubmoduleOption', 
                                        disableSubmodules: false, 
                                        parentCredentials: true, 
                                        recursiveSubmodules: true, 
                                        reference: '', 
                                        trackingSubmodules: true]], 
                          submoduleCfg: [], 
                          userRemoteConfigs: [[credentialsId: 'jenkins-ssh-id', 
                              url: 'git@github.com:romanpeters/maintenance-playbooks.git']]])
            }
        }

        stage('Run Ansible Playbook') {
            steps {
                ansiblePlaybook(
                    playbook: 'status/main.yml',
                    inventory: 'infrastructure/inventory.ini',
                    limit: params.TARGET)
            }
        }
    }

    post {
        success {
            echo 'Ansible playbook executed successfully'
            }
        failure {
            script {
                def msg = "Some of your servers seem offline"
                sh "curl -d '${msg}' ${NOTIFY_URL}"
                echo "${msg}"
            }
        }
    }
}
