pipeline {
    agent any

    parameters {
        choice(choices: ['default', 'all', 'nuc'],
               description: "Choose which host or host group.",
               name: 'TARGET')
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout your source code from version control
                checkout scm
            }
        }

        stage('Fetch Inventory') {
            steps {
                // Clone the Git repository using SSH
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: '*/main']],
                    extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'infrastructure']]
                ])
            }
        }

        stage('Run Ansible Playbook') {
            steps {
                ansiblePlaybook(
                    playbook: 'status/main.yml',
                    inventory: 'infrastructure/inventory.ini',
                    limit: params.TARGET)
            }
        }
    }

    post {
        success {
            echo 'Ansible playbook executed successfully'
            }
        failure {
            script {
                def msg = "Some of your servers seem offline"
                sh "curl -d '${msg}' ${NOTIFY_URL}"
                echo "${msg}"
            }
        }
    }
}
