---
- name: Ping hosts
  hosts: all:!unreachable
  gather_facts: false

  tasks:
    - name: Ping hosts
      ansible.builtin.ping:

    - name: Print skipped hosts
      ansible.builtin.debug:
        var: groups['unreachable']
