---
- name: Install packages
  become: true
  ansible.builtin.apt:
    name:
      - vim
      - git
      - tmux
      - lolcat
      - toilet
      - cowsay
      - sl
    state: present
  tags: packages
