---
- name: Create user
  ansible.builtin.user:
    name: "{{ username }}"
    state: present
    createhome: true

- name: Add to sudoers file
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/{{ username }}
    line: "{{ username }} ALL=(ALL:ALL) NOPASSWD:ALL"
    create: true

- name: Set permissions on sudoers file
  ansible.builtin.file:
    path: /etc/sudoers.d/{{ username }}
    owner: root
    group: root
    mode: "0440"

- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: /home/{{ username }}/.ssh
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0700"

- name: Ensure authorized_keys file exists
  ansible.builtin.file:
    path: /home/{{ username }}/.ssh/authorized_keys
    state: touch
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0600"

- name: Add specific SSH key to authorized_keys
  ansible.builtin.lineinfile:
    path: /home/{{ username }}/.ssh/authorized_keys
    line: "{{ lookup('file', 'files/id_rsa.pub') }}"
    create: true
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0600"

- name: Create SSH config file
  ansible.builtin.copy:
    src: ssh_config
    dest: /home/{{ username }}/.ssh/config
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0600"
