---
- name: Install Zsh
  package:
    name: zsh
    state: present

- name: Clone Oh My Zsh repository
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "/home/{{ username }}/.oh-my-zsh"
  become_user: "{{ username }}"

- name: Change user's shell to Zsh
  user:
    name: "{{ username }}"
    shell: /bin/zsh

