---
- name: Install Zsh
  package:
    name: zsh
    state: present

- name: Clone Oh My Zsh repository
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "/home/{{ username }}/.oh-my-zsh"
  ignore_errors: true

- name: Set owner and group for cloned directory
  file:
    path: "/home/{{ username }}/.oh-my-zsh"
    owner: "{{ username }}"
    group: "{{ username }}"
    recurse: yes

- name: Change user's shell to Zsh
  user:
    name: "{{ username }}"
    shell: /bin/zsh

