---
- name: Clear files
  ansible.builtin.shell: /bin/rm -rf {{ item }}/*
  loop:
    - /mnt/media/movies/.deleted
    - /mnt/media/tvseries/.deleted
    - /mnt/media/downloads/incomplete
    - /mnt/media/downloads/complete
